name: homeworkoutapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1
  eva_icons_flutter:
  moor_flutter: ^2.1.1
  flutter_tts: ^0.8.5
  language_pickers: ^0.2.0+1
  table_calendar:
  charts_flutter: ^0.9.0
  flutter_sparkline:
  day_selector:



dev_dependencies:

  flutter_test:
    sdk: flutter
  build_runner:
  moor_generator: ^2.1.1

flutter:

  uses-material-design: true

  assets:
    - assets/fourmintabata.jpg
    - assets/splashScreen.jpeg
    - assets/bottomSplashImage.png
    - assets/drawerImage.jpg
    - assets/sevenfour/sevenfour1.jpg
    - assets/sevenfour/sevenfour2.jpg
    - assets/advance/advance1.jpg
    - assets/advance/advance2.jpg
    - assets/advance/advance3.jpg
    - assets/advance/advance4.jpg
    - assets/advance/advance5.jpg
    - assets/inter/inter1.jpg
    - assets/inter/inter2.jpg
    - assets/inter/inter3.jpg
    - assets/inter/inter4.jpg
    - assets/inter/inter5.jpg
    - assets/beginner/beginner1.jpg
    - assets/beginner/beginner2.jpg
    - assets/beginner/beginner3.jpg
    - assets/beginner/beginner4.jpg
    - assets/beginner/beginner5.jpg
    - assets/discover.jpg
    - assets/pickforyou/pickforyou7.jpg
    - assets/pickforyou/pickforyou8.jpg
    - assets/pickforyou/pickforyou9.jpg
    - assets/pickforyou/pickforyou6.png
    - assets/pickforyou/pickforyou10.jpg
    - assets/pickforyou/pickforyou1.jpg
    - assets/pickforyou/pickforyou2.jpg
    - assets/pickforyou/pickforyou3.jpg
    - assets/pickforyou/pickforyou4.jpg
    - assets/pickforyou/pickforyou5.jpg
    - assets/fastwork/fastwork1.jpg
    - assets/fastwork/fastwork2.jpg
    - assets/fastwork/fastwork3.jpg
    - assets/fastwork/fastwork4.jpg
    - assets/fastwork/fastwork5.jpg
    - assets/fastwork/fastwork6.jpg
    - assets/withequipment.jpg
    - assets/stretch/stretch1.jpg
    - assets/stretch/stretch2.jpg
    - assets/stretch/stretch3.jpg
    - assets/stretch/stretch4.jpg
    - assets/stretch/stretch5.jpg
    - assets/stretch/stretch6.webp
    - assets/stretch/stretch7.jpg
    - assets/stretch/stretch8.jpg
    - assets/stretch/stretch9.jpg
    - assets/stretch/stretch10.jpg
    - assets/exercise/e1.gif
    - assets/exercise/e2.gif
    - assets/exercise/e3.gif
    - assets/exercise/e4.gif
    - assets/exercise/e5.gif
    - assets/exercise/e6.gif
    - assets/exercise/e7.gif
    - assets/exercise/e8.gif
    - assets/exercise/e9.gif
    - assets/exercise/e10.gif
    - assets/exercise/e13.gif
    - assets/exercise/e14.gif
    - assets/exercise/e16.gif
    - assets/exercise/e17.gif
    - assets/exercise/e19.gif
    - assets/exercise/e21.gif
    - assets/exercise/e22.gif
    - assets/exercise/e23.gif
    - assets/exercise/e24.gif
    - assets/exercise/e25.gif
    - assets/exercise/e26.gif
    - assets/exercise/e27.gif
    - assets/exercise/e28.gif
    - assets/exercise/e31.gif
    - assets/exercise/e32.gif
    - assets/exercise/e34.gif
    - assets/exercise/e35.gif
    - assets/exercise/e39.gif
    - assets/exercise/e42.gif
    - assets/exercise/e43.gif
    - assets/exercise/e44.gif
    - assets/exercise/e45.gif
    - assets/exercise/e47.gif
    - assets/exercise/e49.gif
    - assets/exercise/e50.gif
    - assets/congrats.gif
    - assets/globe.png
    - assets/gift.png
    - assets/no.png
    - assets/gocoronago.png







  # Tadd assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
